[huanxin]
app_key =
client_id =
client_secret =
default_rest = http://a1.easemob.com
token =
last_get_time = 00000000
last_message_time = 2017082802

[db]
db_host = 127.0.0.1
db_user = root
db_password = root
db_database = root
db_table = root

